### ISSUE TITLE
What happens when attempting to push content to a file that *does* already exist?

### ISSUE THREAD

**Issue by gobbletown** [lizard-heart/obsidian-note-content-pusher#2]
That is, can the plugin identify if a file with the name already exists in the vault?

If no, then current process.

If yes, then prepend/append {content} per:
- _Plugin settings_--top of note, bottom of note, after user-defined mark like "___"
- _Inline_--top of note = "key" ; bottom of note = "key"

**Comment by lizard-heart** [comment]
Hey, thanks so much for the feedback. I just pushed a new release with the basic functionality of adding content to an existing note. It also includes the plugin setting to add the content at the beginning or end. More inline settings will be added to the next release.
