### ISSUE TITLE
[Request] Add aliases to existing files as well

### ISSUE THREAD

**Issue by DeutscheGabanna** [lizard-heart/obsidian-note-content-pusher#5]
The language I'm using inflects many of its words. Even I create, hypothetically, a "John Doe" note, depending on whether it's a subject or an object, it may have to be referenced as "Johna Doe'a", for example.

If I reference it like so:
```
[[John Doe|Johna Doe'a]]
```
the alias won't get saved in the YAML frontmatter.

I'd like to use your plugin to do this job and add the aliases while I reference the existing notes. It'll speed up the reference process, because now I won't have to go into the note to edit the YAML myself.

**Comment by lizard-heart** [comment]
I believe if you add it like this `[[John Doe|>>Johna Doe'a]]>>{}` it will do it correctly, but I agree that is a little convoluted.

**Comment by lizard-heart** [comment]
This will be easier in the new release.

**Comment by pawel-ilnicki** [comment]
> I believe if you add it like this `[[John Doe|>>Johna Doe'a]]>>{}` it will do it correctly, but I agree that is a little convoluted.

I followed this method before because it was already in the documentation (unless I'm not seeing a slight change in the syntax?). And it didn't work. After running the script the reference got glitched, and no alias was added to YAML.

Waiting eagerly for next release then.
