### ISSUE TITLE
Release as community plugin

### ISSUE THREAD

**Issue by crazymedguy** [lizard-heart/obsidian-note-content-pusher#6]
Just wondering if this will appear in community plugins anytime soon? Thanks!

**Comment by lizard-heart** [comment]
Yes. I have been quite busy, but I will resolve some issues and submit to the plugin repository soon. In the meantime, you can install directly or with BRAT.

**Comment by lizard-heart** [comment]
Just responding again to let you know that the plugin is finally available as an official community plugin within the app!
